# EKF Configuration for SmartCar Local Localization
# Fuses wheel odometry and IMU data for improved pose estimation

ekf_filter_node:
  ros__parameters:
    use_sim_time: True
    ### Frequency and Delays ###
    frequency: 50.0  # Filter update frequency in Hz
    sensor_timeout: 0.1  # Time to wait for sensor data before throwing an error
    two_d_mode: true  # Robot operates in 2D plane

    ### Frames ###
    map_frame: map
    odom_frame: odom
    base_link_frame: base_footprint
    world_frame: odom  # Use odom as the world frame for local localization

    ### Sensor Topics ###

    # Wheel Odometry (from assignment: /smart_car/wheel/odom)
    odom0: /smart_car/wheel/odom
    odom0_config: [true,  true,  false,    # x, y, z position
                   false, false, true,     # roll, pitch, yaw orientation  
                   true,  true,  false,     # x_dot, y_dot, z_dot velocity
                   false, false, true,      # roll_dot, pitch_dot, yaw_dot angular velocity
                   false, false, false]     # x_ddot, y_ddot, z_ddot acceleration
    odom0_differential: false  # Use absolute measurements
    odom0_relative: false
    odom0_queue_size: 10

    # IMU Sensor (from Gazebo) - disabled for standalone
    # imu0: /imu
    # imu0_config: [false, false, false,     # x, y, z position (not provided by IMU)
    #               false, false, false,      # roll, pitch, yaw orientation (only yaw useful in 2D)
    #               false, false, false,      # x_dot, y_dot, z_dot velocity
    #               false, false, true,       # roll_dot, pitch_dot, yaw_dot angular velocity
    #               true,  true,  false]      # x_ddot, y_ddot, z_ddot linear acceleration
    # imu0_differential: false
    # imu0_relative: false
    # imu0_queue_size: 10
    # imu0_remove_gravitational_acceleration: true  # Remove gravity from IMU readings

    ### Process Noise Covariance ###
    # Higher values mean we trust the process model less
    process_noise_covariance: [0.05, 0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,
                           0.0,  0.05, 0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,
                           0.0,  0.0,  0.06, 0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,
                           0.0,  0.0,  0.0,  0.03, 0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,
                           0.0,  0.0,  0.0,  0.0,  0.03, 0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,
                           0.0,  0.0,  0.0,  0.0,  0.0,  0.06, 0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,
                           0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.025, 0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,
                           0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.025, 0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,
                           0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.04, 0.0,  0.0,  0.0,  0.0,  0.0,  0.0,
                           0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.01, 0.0,  0.0,  0.0,  0.0,  0.0,
                           0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.01, 0.0,  0.0,  0.0,  0.0,
                           0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.02, 0.0,  0.0,  0.0,
                           0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.01, 0.0,  0.0,
                           0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.01, 0.0,
                           0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.015]

    ### Initial State Covariance ###
    # Uncertainty in initial state estimate
    initial_estimate_covariance: [1e-9, 0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,
                              0.0,  1e-9, 0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,
                              0.0,  0.0,  1e-9, 0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,
                              0.0,  0.0,  0.0,  1e-9, 0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,
                              0.0,  0.0,  0.0,  0.0,  1e-9, 0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,
                              0.0,  0.0,  0.0,  0.0,  0.0,  1e-9, 0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,
                              0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  1e-9, 0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,
                              0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  1e-9, 0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,
                              0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  1e-9, 0.0,  0.0,  0.0,  0.0,  0.0,  0.0,
                              0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  1e-9, 0.0,  0.0,  0.0,  0.0,  0.0,
                              0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  1e-9, 0.0,  0.0,  0.0,  0.0,
                              0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  1e-9, 0.0,  0.0,  0.0,
                              0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  1e-9, 0.0,  0.0,
                              0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  1e-9, 0.0,
                              0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  1e-9]

    ### Additional Parameters ###
    use_control: false  # Not using control input
    stamped_control: false
    control_timeout: 0.2

    # Publishing options
    publish_tf: true  # Publish transform from odom to base_link
    publish_acceleration: false

    # Smoothing (use for better performance with delayed sensor data)
    smooth_lagged_data: false
    history_length: 0.0

    # Debug
    print_diagnostics: true
    debug: false
    debug_out_file: /tmp/ekf_debug.txt
